#!/usr/bin/env python3
"""Convert one or more 8-bit unsigned mono PCM WAV files into a single C
header that embeds them as `static const uint8_t name_pcm[]` arrays.

Usage:
    python3 wav_to_c.py <out.h> <name1>=<file1.wav> [<name2>=<file2.wav>] ...

Each WAV must be 8 kHz, 8-bit unsigned, mono. Generate with:
    say -v Samantha "..." -o /tmp/x.aiff
    afconvert /tmp/x.aiff /tmp/x.wav -d UI8@8000 -c 1 -f WAVE
"""
import sys
import wave
from pathlib import Path


def emit_clip(out, name: str, wav_path: Path) -> int:
    with wave.open(str(wav_path), "rb") as wf:
        if wf.getnchannels() != 1 or wf.getsampwidth() not in (1, 2):
            raise SystemExit(
                f"{wav_path}: must be 8-bit or 16-bit mono "
                f"(got {wf.getsampwidth()*8}-bit, {wf.getnchannels()} ch)"
            )
        rate = wf.getframerate()
        sampwidth = wf.getsampwidth()
        frames = wf.readframes(wf.getnframes())

    n_samples = len(frames) // sampwidth
    out.write(f"\n/* {wav_path.name}: {n_samples} samples @ {rate} Hz, {sampwidth*8}-bit */\n")
    if sampwidth == 1:
        out.write(f"static const uint8_t {name}_pcm[] = {{\n")
    else:
        out.write(f"static const int16_t {name}_pcm[] = {{\n")
    if sampwidth == 1:
        for i in range(0, len(frames), 16):
            chunk = frames[i:i + 16]
            out.write("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",\n")
    else:
        # WAV 16-bit is signed little-endian
        import struct
        samples = struct.unpack("<" + "h" * n_samples, frames)
        for i in range(0, n_samples, 12):
            chunk = samples[i:i + 12]
            out.write("    " + ", ".join(f"{s:6d}" for s in chunk) + ",\n")
    out.write("};\n")
    out.write(f"#define {name.upper()}_PCM_LEN ({n_samples}u)\n")
    out.write(f"#define {name.upper()}_PCM_BITS ({sampwidth * 8}u)\n")
    return rate


def main(argv):
    if len(argv) < 3:
        print(__doc__)
        sys.exit(1)

    out_path = Path(argv[1])
    clips = []
    for arg in argv[2:]:
        name, _, path = arg.partition("=")
        clips.append((name, Path(path)))

    with open(out_path, "w") as out:
        out.write("/* Auto-generated by desktop/wav_to_c.py — do not edit. */\n")
        out.write("#ifndef __AUDIO_CLIPS_H__\n#define __AUDIO_CLIPS_H__\n\n")
        out.write("#include <stdint.h>\n")
        rate_marker = "    /* RATE_PLACEHOLDER */\n"
        out.write(rate_marker)
        rates = []
        for name, path in clips:
            rates.append(emit_clip(out, name, path))
        out.write("\n#endif /* __AUDIO_CLIPS_H__ */\n")

    if rates and len(set(rates)) != 1:
        raise SystemExit(f"all clips must share one sample rate, got {sorted(set(rates))}")
    rate = rates[0] if rates else 8000

    text = out_path.read_text().replace(
        rate_marker, f"#define AUDIO_CLIP_RATE_HZ ({rate}u)\n"
    )
    out_path.write_text(text)

    print(f"wrote {out_path} with {len(clips)} clip(s)")


if __name__ == "__main__":
    main(sys.argv)
